id: IE4C941A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T23:51:33+00:00'
last_modified: '2022-06-07T18:53:19.097469+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20703
  title: བོད་སྐད། ལོ་རིམ་བཞི་པ།༼ སྟོད་སྨད།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    74DC:
      image_group_id: I8LS20805
      title: ''
      total_pages: 77
      order: 1
      base_file: 74DC.txt
    B531:
      image_group_id: I8LS20806
      title: ''
      total_pages: 146
      order: 2
      base_file: B531.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
